### ISSUE TITLE
Isort fails with isort: command not found

### ISSUE THREAD

**Issue by gladykov** [isort/isort-action#24]
Not sure is it my config or isort bug...

![2021-06-29_18h08_10](https://user-images.githubusercontent.com/24669884/123831949-1f697180-d905-11eb-8118-8f77aee813a8.png)

and this is my action.yml file:

```
---
on:
  push:
    branches: [dev, master]
  pull_request:
    branches: [dev, master]
name: Run unit tests, check code style, and upload coverage
jobs:
  test-check-code-style-and-upload-coverage:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Prepare isort
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Execute isort
      uses: jamescurtin/isort-action@master
      with:
        requirementsFiles: "requirements.txt"
```
