### ISSUE TITLE
Error: Unable to process file command 'output' successfully

### ISSUE THREAD

**Issue by grainnemcknight** [isort/isort-action#57]
Hey, using this action in our codebase and as of yesterday it has been failing to run with `Error: Unable to process file command 'output' successfully.` This is our set-up:
```
  isort:
    runs-on: ubuntu-latest
    name: isort
    steps:
      - uses: actions/checkout@v2
      - uses: isort/isort-action@master
        with:
          configuration: "black"
```
Running isort with the same configuration on our codebase locally works and returns no errors and when we reverted to `-uses: isort/isort-action@v1.0.0` it ran successfully. 
The issue appears to have appeared with[ this commit](https://github.com/isort/isort-action/commit/cad8d89379c2bacf535f8ba4e82ef33da20a644a)
