### ISSUE TITLE
How to run isort-action so that it auto-fixes the code?

### ISSUE THREAD

**Issue by Nagidal** [isort/isort-action#64]
I am trying to run isort in a gitub-workflow in a way that it fixes the code rather than ends the workflow if the imports are unsorted:

This is my workflow setup:
```yml
name: Lint

on:
  push:
    branches:
      - testlint
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - testlint

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out git repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install black isort
      - name: Run Black
        uses: wearerequired/lint-action@v2.1.0
        with:
          auto_fix: true
          black: true
          black_auto_fix: true
      - name: Run isort
        uses: isort/isort-action@v1.1.0
        with:
          configuration: ""
```

Output log of the github action:
```
  Successfully installed attrs-22.1.0 cached-property-1.5.2 cerberus-1.3.4 certifi-2022.9.24 charset-normalizer-2.1.1 colorama-0.4.6 distlib-0.3.6 docopt-0.6.2 idna-3.4 pep517-0.13.0 pip-api-0.0.30 pipreqs-0.4.11 plette-0.4.2 requests-2.28.1 requirementslib-2.1.0 tomlkit-0.11.6 urllib3-1.26.12 vistir-0.6.1 yarg-0.1.9
Run /home/runner/work/_actions/isort/isort-action/v1.1.0/bin/run_isort  .
  /home/runner/work/_actions/isort/isort-action/v1.1.0/bin/run_isort  .
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.11.0/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.11.0/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.0/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.0/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.0/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.0/x64/lib
Running isort .
```
And that's it isort does not output anything anymore, the code is unsorted and stays unsorted.

I tried to run it with the default configuration (i.e. `--check-only --diff`). Then it runs, detects that the imports are wrongly sorted, throws the error, and the workflow ends.
